version: '3'

services:

  mysql:
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/db:/var/lib/mysql
      - ./.docker/mysql/scripts/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
